export const SET_NEW_NOTICE_NUMBER = "SET_NEW_NOTICE_NUMBER";
export const CLEAR_NEW_NOTICE_NUMBER = "CLEAR_NEW_NOTICE_NUMBER";
export const CREATE_CONNECTION = "CREATE_CONNECTION";
export const SET_CONNECTING_HUB = "SET_CONNECTING_HUB";