version: '3'
networks: 
  nvmanh-network:
    external: true
services:
  e-contact:
    image: e-contact
    container_name: e-contact
    restart: always
    networks:
      - nvmanh-network
    ports:
      - '9002:80'
    build:
      context: .
      dockerfile: MS.eContact.Web/Dockerfile
